### ISSUE TITLE
Sort Counters per Continent #10

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#20]
**As a** travel enthusiast

**I want to** see the counters of visited countries per continent sorted alphabetically 

**so that** I can easily track my progress of visited countries

![Image](https://user-images.githubusercontent.com/123647583/231108114-cbd74298-9fc7-4c40-b5f3-bbca2e6114e4.png)

#### Acceptance criteria

- [X] The continents are sorted alphabetically

#### Tasks

- [X] insert the .sort() method on the `CounterContinent` component

**Comment by rabe200** [comment]
lgtm!
