### ISSUE TITLE
Add Local storage to form #15

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#31]
**As a** travel enthusiast

**I want to** be able to see the details I added to the countries I want to visit permanently

**so that** I won't have to enter everything again when re-loading the page

![Image](https://user-images.githubusercontent.com/123647583/232334158-0f827b87-5cda-4783-a036-88e579abca43.png)

- [X] the submitted form data is saved in localStorage
- [X] when reloading the page the data is still displayed

#### Tasks

- [X] use useLocalStorage

**Comment by FrankSiyli** [comment]
LocalStorage forever!
