### ISSUE TITLE
Details page: Adding current local time #20

### ISSUE THREAD

**Issue by AnjaSiewert** [AnjaSiewert/capstone_globehopper#34]
#### Value Proposition

**As a** travel enthusiast

**I want to** see the current local time on the details page

**so that** I will immediately see the local time i.o. only the timezone atm

![Image](https://user-images.githubusercontent.com/123647583/232579674-66ae662f-4bda-4875-a4c9-67ba0d3a182e.png)

#### Acceptance Criteria

- [X] on details page the local time is displayed

#### Tasks

- [X] Add a function that returns the UTC time from the API into the current local time in the respective country

**Comment by toshydev** [comment]
Little typo:
"so that I will immediately **see** the local time i.o. only the timezone atm"
Rest LGTM ✅
